title: "Rauf Shah, PhD"
description: "Health Data Science • Clinical Genomics • Public Health Informatics"
url: "https://arshah18.github.io"
baseurl: ""
permalink: pretty
timezone: "America/Chicago"

# Disable any theme; do NOT set `remote_theme`
theme: just-the-docs

markdown: kramdown
kramdown:
  input: GFM

theme: just-the-docs

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
