# _config.yml
title: "arshah18"
url: "https://arshah18.github.io"
baseurl: ""

theme: null
remote_theme: just-the-docs/just-the-docs@v0.6.2

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# (Optional) just-the-docs options
color_scheme: light
search_enabled: true
