title: "Rauf Shah, PhD"
description: "Health Data Science • Clinical Genomics • Public Health Informatics"
url: "https://arshah18.github.io"
baseurl: ""
permalink: pretty
timezone: "America/Chicago"

# Disable any theme; do NOT set `remote_theme`
theme: null

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
