# .github/workflows/pages.yml
name: Build & Deploy Pages
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: "development:test"

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
